### ISSUE TITLE
Strange route through the ocean

### ISSUE THREAD

**Issue by kilostone** [Bokjan/BravoFinder#13]
The project works well. But some problem occur when calculating some route through the ocean (like KSFO-EGLL, LFPG-KJFK, KSFO-LFPG)
Some of route will have a very long loop. And some route will through 'NZSP'(-89.981947,-144.063631).

**Comment by Bokjan** [comment]
Known issue.

Refactoring is under consideration.

**Comment by Bokjan** [comment]
I've rewritten the navigation data parser, and it won't stuck when planning routes like you mentioned above(`KSFO`-`EGLL`). Instead, the result will be INF(infinity). That's because there's no SID or STAR program connecting to destination-reachable route.

In the new version of BravoFinder, I connect SID fixes as approach legs with route named `DCT`, and STAR fixes as departure legs. This is a kind of relief, but not a good solution. For example , currently I still cannot get a route from `KSFO` to `EGLL`. 

This comment is a detailed explanation for your issue.
