### ISSUE TITLE
有什么方法可以将这个查找器和php结合起来吗

### ISSUE THREAD

**Issue by dextercai** [Bokjan/BravoFinder#7]
有什么方法可以将这个查找器和php结合起来吗

---

How can I combine _BravoFinder_ with _php_?

**Comment by Bokjan** [comment]
Thank you for opening an issue.

Though I didn't directly support persistence, and no interface for other languages, you can still use it in any kind of projects. I can come up with this solution for you: 
1. Making graph data inside BravoFinder persistent
2. Endless main loop
3. Using socket(recommend), filesystem or other type of inter process communications to transfer data

Or you can just simply rewrite BravoFinder in php. It will be much easier than C++ due to no memory management needed.

Don't forget that this repo is under CC-BY-NC 4.0 LICENSE. 😄

---

感谢你开启一个issue。

虽然我没有直接地支持持久化，也没有其他语言的接口，你仍然可以将其用于任何类型的项目。我可以给你想出这样一个解决方案：
1. 使得BravoFinder中的图数据持久化；
2. 主循环死循环；
3. 使用套接字（推荐），文件系统或其他类型的进程间通信方法传输数据。

或者你可以简单地用php重写BravoFinder。因为不需要手动内存管理，这会比C++简单不少。

别忘了这个仓库是基于知识共享-署名-非商业性使用4.0协议的。 😄

**Comment by dextercai** [comment]
待我试试看使用php来重写这个功能，如果我有进展了，我会发一个PR。

**Comment by Bokjan** [comment]
It's easy to do this with v2 library. I'll show you a demonstration later.

**Comment by dextercai** [comment]
I appreciate.
